name: Lint Commit Messages

on:
  push:
  pull_request:

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commit Message Format
        run: |
          REGEXP="^(add|delete|modify|refactor|fix|merge): .+$"
          EXIT_CODE=0

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TITLE="${{ github.event.pull_request.title }}"
            if [[ ! $TITLE =~ $REGEXP ]]; then
              echo "ERROR: PR Title '$TITLE' invalid."
              EXIT_CODE=1
            fi
          fi

          COMMIT_MSG=$(git log -1 --format=%s)
          
          echo "Checking latest commit: $COMMIT_MSG"
          
          if [[ ! $COMMIT_MSG =~ $REGEXP ]]; then
            echo "ERROR: Latest commit message '$COMMIT_MSG' does not match format."
            EXIT_CODE=1
          else
            echo "VALID: '$COMMIT_MSG'"
          fi

          exit $EXIT_CODE